
package ar.com.educacionit.soap.server.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductoWSSoapServiceImplService", targetNamespace = "http://impl.server.soap.educacionit.com.ar/", wsdlLocation = "http://localhost:8000/ws/productos?wsdl")
public class ProductoWSSoapServiceImplService
    extends Service
{

    private final static URL PRODUCTOWSSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTOWSSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PRODUCTOWSSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://impl.server.soap.educacionit.com.ar/", "ProductoWSSoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/ws/productos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTOWSSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PRODUCTOWSSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ProductoWSSoapServiceImplService() {
        super(__getWsdlLocation(), PRODUCTOWSSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public ProductoWSSoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTOWSSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProductoWSSoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTOWSSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public ProductoWSSoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTOWSSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProductoWSSoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductoWSSoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductoWsSoapService
     */
    @WebEndpoint(name = "ProductoWSSoapServiceImplPort")
    public ProductoWsSoapService getProductoWSSoapServiceImplPort() {
        return super.getPort(new QName("http://impl.server.soap.educacionit.com.ar/", "ProductoWSSoapServiceImplPort"), ProductoWsSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductoWsSoapService
     */
    @WebEndpoint(name = "ProductoWSSoapServiceImplPort")
    public ProductoWsSoapService getProductoWSSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.server.soap.educacionit.com.ar/", "ProductoWSSoapServiceImplPort"), ProductoWsSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTOWSSOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PRODUCTOWSSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PRODUCTOWSSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
